

 const catalogo = [
  {
    id: 1,
    titulo: "A múmia",
    tipo: "filme",
    generos: ["Ação", "fantasia"],
    duracaoMinutos: 125,
  },
  {
    id: 2,
    titulo: "Os embalos de sábado à noite",
    tipo: "filme",
    generos: ["Comédia", "musical", "drama"],
    duracaoMinutos: 118,
  },
  {
    id: 3,
    titulo: "Entrevista com o vampiro",
    tipo: "filme",
    generos: ["Terror", "drama", "suspense"],
    duracaoMinutos: 123,
  },
  {
    id: 4,
    titulo: "Interestelar",
    tipo: "filme",
    generos: ["Ficção científica", "drama", "aventura"],
    duracaoMinutos: 169,
  },
  {
    id: 5,
    titulo: "O Senhor dos Anéis: A Sociedade do Anel",
    tipo: "filme",
    generos: ["Fantasia", "aventura", "drama"],
    duracaoMinutos: 178,
  },
  {
    id: 6,
    titulo: "Batman: O Cavaleiro das Trevas",
    tipo: "filme",
    generos: ["Ação", "crime", "drama", "suspense"],
    duracaoMinutos: 152,
  },
  {
    id: 7,
    titulo: "Jurassic Park",
    tipo: "filme",
    generos: ["Aventura", "ficção científica", "suspense"],
    duracaoMinutos: 127,
  },
  {
    id: 8,
    titulo: "Titanic",
    tipo: "filme",
    generos: ["Romance", "drama"],
    duracaoMinutos: 194,
  },
  {
    id: 9,
    titulo: "Matrix",
    tipo: "filme",
    generos: ["Ação", "ficção científica", "suspense"],
    duracaoMinutos: 136,
  },
  {
    id: 10,
    titulo: "O Poderoso Chefão",
    tipo: "filme",
    generos: ["Crime", "drama"],
    duracaoMinutos: 175,
  },
  {
    id: 11,
    titulo: "Forrest Gump",
    tipo: "filme",
    generos: ["Drama", "romance", "comédia"],
    duracaoMinutos: 142,
  },
  {
    id: 12,
    titulo: "O Iluminado",
    tipo: "filme",
    generos: ["Terror", "suspense", "drama"],
    duracaoMinutos: 146,
  },
  {
    id: 13,
    titulo: "Gladiador",
    tipo: "filme",
    generos: ["Ação", "drama", "aventura"],
    duracaoMinutos: 155,
  },
  {
    id: 14,
    titulo: "Harry Potter e a Pedra Filosofal",
    tipo: "filme",
    generos: ["Fantasia", "aventura", "família"],
    duracaoMinutos: 152,
  },
  {
    id: 15,
    titulo: "Homem-Aranha",
    tipo: "filme",
    generos: ["Ação", "aventura", "ficção científica"],
    duracaoMinutos: 121,
  },
  {
    id: 16,
    titulo: "O Rei Leão",
    tipo: "filme",
    generos: ["Animação", "aventura", "drama", "musical"],
    duracaoMinutos: 88,
  },
  {
    id: 17,
    titulo: "Toy Story",
    tipo: "filme",
    generos: ["Animação", "comédia", "aventura", "família"],
    duracaoMinutos: 81,
  },
  {
    id: 18,
    titulo: "Pânico",
    tipo: "filme",
    generos: ["Terror", "suspense", "mistério"],
    duracaoMinutos: 111,
  },
  {
    id: 19,
    titulo: "Jogos Vorazes",
    tipo: "filme",
    generos: ["Ação", "aventura", "ficção científica", "drama"],
    duracaoMinutos: 142,
  },
  {
    id: 20,
    titulo: "De Volta para o Futuro",
    tipo: "filme",
    generos: ["Ficção científica", "aventura", "comédia"],
    duracaoMinutos: 116,
  },
  {
    id: 21,
    titulo: "Piratas do Caribe: A Maldição do Pérola Negra",
    tipo: "filme",
    generos: ["Ação", "aventura", "fantasia", "comédia"],
    duracaoMinutos: 143,
  },
  {
    id: 22,
    titulo: "O Exorcista",
    tipo: "filme",
    generos: ["Terror", "drama", "suspense"],
    duracaoMinutos: 122,
  },
  {
    id: 23,
    titulo: "Django Livre",
    tipo: "filme",
    generos: ["Faroeste", "drama", "ação"],
    duracaoMinutos: 165,
  },
  {
    id: 24,
    titulo: "Clube da Luta",
    tipo: "filme",
    generos: ["Drama", "suspense", "comédia"],
    duracaoMinutos: 139,
  },
  {
    id: 25,
    titulo: "As Branquelas",
    tipo: "filme",
    generos: ["Comédia", "crime"],
    duracaoMinutos: 109,
  },
  {
    id: 26,
    titulo: "O Máskara",
    tipo: "filme",
    generos: ["Comédia", "fantasia", "romance"],
    duracaoMinutos: 101,
  },
  {
    id: 27,
    titulo: "Mad Max: Estrada da Fúria",
    tipo: "filme",
    generos: ["Ação", "aventura", "ficção científica"],
    duracaoMinutos: 120,
  },
  {
    id: 28,
    titulo: "O Silêncio dos Inocentes",
    tipo: "filme",
    generos: ["Crime", "terror", "suspense", "drama"],
    duracaoMinutos: 118,
  },
  {
    id: 29,
    titulo: "Shrek",
    tipo: "filme",
    generos: ["Animação", "comédia", "fantasia", "aventura"],
    duracaoMinutos: 90,
  },
  {
    id: 30,
    titulo: "Vingadores: Ultimato",
    tipo: "filme",
    generos: ["Ação", "aventura", "ficção científica", "drama"],
    duracaoMinutos: 181,
  },
];

module.exports = catalogo;